config/routes.rb
Inspirovation::Application.routes.draw do

  resources :milestones

  resources :favorites

  resources :views

  resources :ratings

  resources :questions

  resources :subideas

  resources :maps

  resources :ideas

  devise_for :users

  
  
  match 'subideas/new/:extra' => 'subideas#new'
  match 'subideas/new/:extra/:parent_id' => 'subideas#new'
  
  match 'questions/new/:idea_id' => 'questions#new', :as => 'new_question'
  
  match 'ideas/:idea_id/voteup' => 'ratings#voteup', :as => 'voteup'
  match 'ideas/:idea_id/votedown' => 'ratings#votedown', :as => 'votedown'
  
  match 'milestones/new/:idea_id' => 'milestones#new', :as => 'new_milestone'
  match 'milestones/:id/edit/:idea_id' => 'milestones#edit', :as => 'edit_milestone'
  
  match 'ideas/:idea_id/add_my_favorite' => 'favorites#add_my_favorite', :as => 'add_my_favorite'
  
  match 'home/:action' => 'home#:action', :as => 'home'
  
  root :to => "home#index"
end

app/models/map.rb
class Map < ActiveRecord::Base
  belongs_to :subidea
  
  validates :cellw, :presence => true
  validates :cellh, :presence => true
  validates :dir, :presence => true
  validates :ico_type, :presence => true
  validates :subidea_id, :presence => true
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  # GET /maps
  # GET /maps.xml
  def index
    @maps = Map.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @maps }
    end
  end

  # GET /maps/1
  # GET /maps/1.xml
  def show
    @map = Map.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @map }
    end
  end

  # GET /maps/new
  # GET /maps/new.xml
  def new
    @map = Map.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @map }
    end
  end

  # GET /maps/1/edit
  def edit
    @map = Map.find(params[:id])
  end

  # POST /maps
  # POST /maps.xml
  def create
    @map = Map.new(params[:map])

    respond_to do |format|
      if @map.save
        format.html { redirect_to(@map, :notice => 'Map was successfully created.') }
        format.xml  { render :xml => @map, :status => :created, :location => @map }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @map.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /maps/1
  # PUT /maps/1.xml
  def update
    @map = Map.find(params[:id])
    
    respond_to do |format|
      if @map.update_attributes(params[:map])        
        format.html { redirect_to(@map, :notice => 'Map was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @map.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.xml
  def destroy
    @map = Map.find(params[:id])
    @map.destroy

    respond_to do |format|
      format.html { redirect_to(maps_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_form.html.erb
<%= form_for(@map) do |f| %>
  <% if @map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% @map.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cellw %><br />
    <%= f.text_field :cellw %>
  </div>
  <div class="field">
    <%= f.label :cellh %><br />
    <%= f.text_field :cellh %>
  </div>
  <div class="field">
    <%= f.label :dir %><br />
    <%= f.text_field :dir %>
  </div>
  <div class="field">
    <%= f.label :ico_type %><br />
    <%= f.text_field :ico_type %>
  </div>
  <div class="field">
    <%= f.label :subidea_id %><br />
    <%= f.text_field :subidea_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/maps/edit.html.erb
<h1>Editing map</h1>

<%= render 'form' %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

app/views/maps/index.html.erb
<h1>Listing maps</h1>

<table>
  <tr>
    <th>Cellw</th>
    <th>Cellh</th>
    <th>Dir</th>
    <th>Type</th>
    <th>Subidea</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @maps.each do |map| %>
  <tr>
    <td><%= map.cellw %></td>
    <td><%= map.cellh %></td>
    <td><%= map.dir %></td>
    <td><%= map.ico_type %></td>
    <td><%= map.subidea_id %></td>
    <td><%= link_to 'Show', map %></td>
    <td><%= link_to 'Edit', edit_map_path(map) %></td>
    <td><%= link_to 'Destroy', map, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Map', new_map_path %>

app/views/maps/new.html.erb
<h1>New map</h1>

<%= render 'form' %>

<%= link_to 'Back', maps_path %>

app/views/maps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cellw:</b>
  <%= @map.cellw %>
</p>

<p>
  <b>Cellh:</b>
  <%= @map.cellh %>
</p>

<p>
  <b>Dir:</b>
  <%= @map.dir %>
</p>

<p>
  <b>Type:</b>
  <%= @map.ico_type %>
</p>

<p>
  <b>Subidea:</b>
  <%= @map.subidea_id %>
</p>


<%= link_to 'Edit', edit_map_path(@map) %> |
<%= link_to 'Back', maps_path %>