config/routes.rb
Inspirovation::Application.routes.draw do

  resources :milestones

  resources :favorites

  resources :views

  resources :ratings

  resources :questions

  resources :subideas

  resources :maps

  resources :ideas

  devise_for :users

  
  
  match 'subideas/new/:extra' => 'subideas#new'
  match 'subideas/new/:extra/:parent_id' => 'subideas#new'
  
  match 'questions/new/:idea_id' => 'questions#new', :as => 'new_question'
  
  match 'ideas/:idea_id/voteup' => 'ratings#voteup', :as => 'voteup'
  match 'ideas/:idea_id/votedown' => 'ratings#votedown', :as => 'votedown'
  
  match 'milestones/new/:idea_id' => 'milestones#new', :as => 'new_milestone'
  match 'milestones/:id/edit/:idea_id' => 'milestones#edit', :as => 'edit_milestone'
  
  match 'ideas/:idea_id/add_my_favorite' => 'favorites#add_my_favorite', :as => 'add_my_favorite'
  
  match 'home/:action' => 'home#:action', :as => 'home'
  
  root :to => "home#index"
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea
  
  validates :idea_id, :presence => true
  validates :user_id, :presence => true
  validates :rating_type, :presence => true  
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  # GET /ratings
  # GET /ratings.xml
  def index
    @ratings = Rating.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @ratings }
    end
  end

  # GET /ratings/1
  # GET /ratings/1.xml
  def show
    @rating = Rating.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @rating }
    end
  end

  # GET /ratings/new
  # GET /ratings/new.xml
  def new
    @rating = Rating.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @rating }
    end
  end

  # GET /ratings/1/edit
  def edit
    @rating = Rating.find(params[:id])
  end

  # POST /ratings
  # POST /ratings.xml
  def create
    @rating = Rating.new(params[:rating])

    respond_to do |format|
      if @rating.save
        format.html { redirect_to(@rating, :notice => 'Rating was successfully created.') }
        format.xml  { render :xml => @rating, :status => :created, :location => @rating }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @rating.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ratings/1
  # PUT /ratings/1.xml
  def update
    @rating = Rating.find(params[:id])

    respond_to do |format|
      if @rating.update_attributes(params[:rating])
        format.html { redirect_to(@rating, :notice => 'Rating was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @rating.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.xml
  def destroy
    @rating = Rating.find(params[:id])
    @rating.destroy

    respond_to do |format|
      format.html { redirect_to(ratings_url) }
      format.xml  { head :ok }
    end
  end
  
  def vote (idea_id,rating_type)
    # check to see if user already rated
    check = Rating.where(:idea_id => idea_id, :user_id => current_user.id) 
        
    error = false
    
    if check.count > 0
      error = true
    end  
    
    # check to see if its the same user
    if Idea.find(idea_id).user.id == current_user.id
      error = true
    end
    
    if error == false
      @rating = Rating.new
      @rating.idea_id = params[:idea_id]
      @rating.user_id = current_user.id
      @rating.rating_type = rating_type
      @rating.save
    end 
  end
  
  # vote up
  def voteup 
    vote(params[:idea_id],1)
        
    respond_to do |format|
      format.html { redirect_to(idea_path(params[:idea_id])) }
    end
  end
  
  # vote down
  def votedown
    vote(params[:idea_id],2)
        
    respond_to do |format|
      format.html { redirect_to(idea_path(params[:idea_id])) }
    end
  end
  
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rating_type %><br />
    <%= f.text_field :rating_type %>
  </div>
  <div class="field">
    <%= f.label :idea_id %><br />
    <%= f.text_field :idea_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<h1>Listing ratings</h1>

<table>
  <tr>
    <th>Rating type</th>
    <th>Idea</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ratings.each do |rating| %>
  <tr>
    <td><%= rating.rating_type %></td>
    <td><%= rating.idea_id %></td>
    <td><%= rating.user_id %></td>
    <td><%= link_to 'Show', rating %></td>
    <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
    <td><%= link_to 'Destroy', rating, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1>New rating</h1>

<%= render 'form' %>

<%= link_to 'Back', ratings_path %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Rating type:</b>
  <%= @rating.rating_type %>
</p>

<p>
  <b>Idea:</b>
  <%= @rating.idea_id %>
</p>

<p>
  <b>User:</b>
  <%= @rating.user_id %>
</p>


<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>