config/routes.rb
Inspirovation::Application.routes.draw do

  resources :milestones

  resources :favorites

  resources :views

  resources :ratings

  resources :questions

  resources :subideas

  resources :maps

  resources :ideas

  devise_for :users

  
  
  match 'subideas/new/:extra' => 'subideas#new'
  match 'subideas/new/:extra/:parent_id' => 'subideas#new'
  
  match 'questions/new/:idea_id' => 'questions#new', :as => 'new_question'
  
  match 'ideas/:idea_id/voteup' => 'ratings#voteup', :as => 'voteup'
  match 'ideas/:idea_id/votedown' => 'ratings#votedown', :as => 'votedown'
  
  match 'milestones/new/:idea_id' => 'milestones#new', :as => 'new_milestone'
  match 'milestones/:id/edit/:idea_id' => 'milestones#edit', :as => 'edit_milestone'
  
  match 'ideas/:idea_id/add_my_favorite' => 'favorites#add_my_favorite', :as => 'add_my_favorite'
  
  match 'home/:action' => 'home#:action', :as => 'home'
  
  root :to => "home#index"
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea
  
  validates :idea_id, :presence => true
  validates :user_id, :presence => true
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user
  has_many :subideas  
  has_many :questions
  has_many :views
  has_many :favorites
  has_many :ratings
  has_many :milestones
   
  validates :title, :presence => true
  validates :statement, :presence => true, :length => { :maximum => 120 }
  validates :summary, :presence => true
end

app/models/map.rb
class Map < ActiveRecord::Base
  belongs_to :subidea
  
  validates :cellw, :presence => true
  validates :cellh, :presence => true
  validates :dir, :presence => true
  validates :ico_type, :presence => true
  validates :subidea_id, :presence => true
end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
	belongs_to :idea
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :idea
  
  validates :title, :presence => true
  validates :idea_id, :presence => true
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea
  
  validates :idea_id, :presence => true
  validates :user_id, :presence => true
  validates :rating_type, :presence => true  
end

app/models/subidea.rb
class Subidea < ActiveRecord::Base
  belongs_to :idea
  has_one :map
  
  validates :title, :presence => true
  validates :summary, :presence => true
  validates :idea_id, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :ideas
  has_many :views
  has_many :favorites
  has_many :ratings
end

app/models/view.rb
class View < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea
  
  validates :idea_id, :presence => true
  validates :user_id, :presence => true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # if the user is signed in send them to the main inspirovations page
    if user_signed_in?
      redirect_to :controller => "ideas"
    end
  end
  
  def coming_soon
    respond_to do |format|
      format.html # coming_soon.html.erb
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
  def build_idea_map (idea_id)
    # get the sub ideas so we can later find out their maps
    subideas = Subidea.where(:idea_id => idea_id)
        
    # create the map hash
    map = {
      # first column
      1 => {
          1 => '<img src="/images/map_ico_blank.png" />', 
          2 => '<img src="/images/map_ico_blank.png" />',
          3 => '<img src="/images/map_ico_blank.png" />',
          4 => '<img src="/images/map_ico_blank.png" />',
          5 => '<img src="/images/map_ico_blank.png" />'},
      
      2 => {
          1 => '<img src="/images/map_ico_blank.png" />', 
          2 => '<img src="/images/map_ico_blank.png" />',
          3 => '<a href="/subideas/new/123w' + String(idea_id) + '"><img src="/images/map_ico_addW.png"  title="New Medium Idea" /></a>',
          4 => '<img src="/images/map_ico_blank.png" />',
          5 => '<img src="/images/map_ico_blank.png" />'},
      
      3 => {
          1 => '<img src="/images/map_ico_blank.png" />', 
          2 => '<a href="/subideas/new/232n' + String(idea_id) + '"><img src="/images/map_ico_SaddN.png" title="New Small Idea" /></a>',
          3 => '<a href="/ideas/' + String(idea_id) + '"><img src="/images/map_ico_main.png" title="View Big Idea" /></a>',
          4 => '<a href="/subideas/new/234s' + String(idea_id) + '"><img src="/images/map_ico_SaddS.png" title="New Small Idea" /></a>',
          5 => '<img src="/images/map_ico_blank.png" />'},
      
      4 => {
          1 => '<img src="/images/map_ico_blank.png" />', 
          2 => '<img src="/images/map_ico_blank.png" />',
          3 => '<a href="/subideas/new/143e' + String(idea_id) + '"><img src="/images/map_ico_addE.png" title="New Medium Idea" /></a>',
          4 => '<img src="/images/map_ico_blank.png" />',
          5 => '<img src="/images/map_ico_blank.png" />'},
          
      #last column don't forget to end the commas and double check some things like brackets
      5 => {
          1 => '<img src="/images/map_ico_blank.png" />', 
          2 => '<img src="/images/map_ico_blank.png" />',
          3 => '<img src="/images/map_ico_blank.png" />',
          4 => '<img src="/images/map_ico_blank.png" />',
          5 => '<img src="/images/map_ico_blank.png" />'}
    }
    
    subideas.each do |si|
      # get the vars we need
      w = si.map.cellw
      h = si.map.cellh
      dir = si.map.dir.upcase
      ico_type = si.map.ico_type
      
      # figure out the new addition buttons if it is type 1
      case ico_type
      when 1
        # make top and bottom adds
        top = Integer(h) + 1        
        bottom = Integer(h) - 1
        
        # set the south and north addition buttons
        map[Integer(w)][Integer(top)] = '<a href="/subideas/new/2' + String(w) + String(top) + 's' + String(idea_id) + '/' + String(si.id) + '"><img src="/images/map_ico_SaddS.png" title="New Small Idea" /></a>'        
        map[Integer(w)][Integer(bottom)] = '<a href="/subideas/new/2' + String(w) + String(bottom) + 'n' + String(idea_id) + '/' + String(si.id) + '"><img src="/images/map_ico_SaddN.png" title="New Small Idea" /></a>'
        
        # create the different addition buttons        
        case dir
        when "E"
          side = Integer(w) + 1
        when "W"
          side = Integer(w) - 1          
        end
        map[Integer(side)][Integer(h)] = '<a href="/subideas/new/2' + String(side) + String(h) + String(dir) + String(idea_id) + '/' + String(si.id) + '"><img src="/images/map_ico_Sadd' + String(dir) + '.png" title="New Small Idea" /></a>'
        
        # create the submain idea icon
        map[Integer(w)][Integer(h)] = '<a href="/subideas/' + String(si.id) + '"><img src="/images/map_ico_submain.png" /></a>'
      when 2
        # create the sub sub idea icon
        map[Integer(w)][Integer(h)] = '<a href="/subideas/' + String(si.id) + '"><img src="/images/map_ico_Ssub' + dir + '.png" /></a>'
      end     
      # end of the each
    end
           
    # begin building the table 
    html = '' 
    html += '<table>'

    b = 1                                                           # define the b var which are the rows
    until b > 5                                                     # count from 1-5 for the rows
      html += '<tr>'
        a = 1                                                       # define the a var which are the columns
        until a > 5                                                 # count from 1-5 for the columns
          html += '<td>'+ map[Integer(a)][Integer(b)] +'</td>'
          a += 1                                                    # but of course we must increment
        end
      html += '</tr>'
      b += 1                                                        # increment some more cause we're cool like that
    end
    html += '</table>'
    
    # spit out the raw html
    raw html
  end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/subideas_helper.rb
module SubideasHelper
end

app/helpers/views_helper.rb
module ViewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Inspirovation - idea curation and repository</title>
        <%= stylesheet_link_tag :all %>
        <%= javascript_include_tag :defaults %>
        <%= csrf_meta_tag %>
        <%= yield(:head) %>
    </head>
    
    <body>
      <!-- Begin Header -->
      <div id="header_container">
          <div id="header">
              <div id="logo">
                  <a href="/"><img src="/images/logo.png" title="Inspirovation.com - ideas.curated" /></a>
                </div>
                <div id="total">
                  <%= pluralize(Idea.count, "active idea") %> available and counting.
                </div>
                <div class="clear"></div>
            </div>
            <div id="dashboard">
              <div id="actions">
                  <%= 
                  if user_signed_in?
                    link_to 'Create', new_idea_path
                  else
                    link_to "Create", new_user_session_path
                  end   
                  %> 
                  / 
                  <%=
                  if user_signed_in?
                    link_to "Discover", home_path('coming_soon')
                  else
                    link_to "Discover", home_path('coming_soon')
                  end
                  %>
                  / 
                  <%=
                  if user_signed_in?
                    link_to "Develop", home_path('coming_soon')
                  else
                    link_to "Develop", home_path('coming_soon')
                  end
                  %>
                </div>
                <div id="icons">
                  <% if user_signed_in? %>
                    <%= link_to edit_user_registration_path do  %> 
                      <img src='/images/ico_settings.png' /> Settings
                    <% end %>
                    |
                    <%= link_to destroy_user_session_path do  %> 
                      <img src='/images/ico_unlock.png' /> Logout
                    <% end %>
                  <% else %>
                    <%= link_to new_user_session_path do  %> 
                      <img src='/images/ico_lock.png' /> Login
                    <% end %>
                    | 
                    <%= link_to new_user_registration_path do  %> 
                      <img src='/images/ico_register.png' /> Sign Up
                    <% end %>
                  <% end %>
                </div>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>
        <!-- End Header -->
        <!-- Begin Content -->
        <div id="clearall"></div>
        <div id="content_container">
            <ul id="nav">
              <li><%= link_to "Business", home_path('coming_soon') %></li>
                <li><%= link_to "Application", home_path('coming_soon') %></li>
                <li><%= link_to "Entertainment", home_path('coming_soon') %></li>
            </ul>
            <div id="search">
                <form method="post" action="">
                    <input class="text" type="text" value="" />
                    <input class="submit" type="submit" value="Search" disabled="true" />
                </form>
            </div>
            <div class="clear"></div>
            <p class="notice"><% notice %></p>
            <p class="alert"><% alert %></p>
            <div id="content"><%= yield %></div>
        </div>
        <!-- End Content -->
        <!-- Begin Footer -->
        <div class="clear"></div>
        <div id="footer">
          <div class="icons">
            <a href="http://twitter.com/drewry" target="_blank"><img src="/images/twitter_32.png"></a>
            <a href="mailto: dhmorris@gmail.com" target="_blank"><img src="/images/email_32.png"></a>
          </div>
          Inspirovation &copy; 2010.  All Rights Reserved.
        </div>
        <!-- End Footer -->
    </body>
</html>

app/views/views/_form.html.erb
<%= form_for(@view) do |f| %>
  <% if @view.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@view.errors.count, "error") %> prohibited this view from being saved:</h2>

      <ul>
      <% @view.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :idea_id %><br />
    <%= f.text_field :idea_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/views/edit.html.erb
<h1>Editing view</h1>

<%= render 'form' %>

<%= link_to 'Show', @view %> |
<%= link_to 'Back', views_path %>

app/views/views/index.html.erb
<h1>Listing views</h1>

<table>
  <tr>
    <th>Idea</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @views.each do |view| %>
  <tr>
    <td><%= view.idea_id %></td>
    <td><%= view.user_id %></td>
    <td><%= link_to 'Show', view %></td>
    <td><%= link_to 'Edit', edit_view_path(view) %></td>
    <td><%= link_to 'Destroy', view, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New View', new_view_path %>

app/views/views/new.html.erb
<h1>New view</h1>

<%= render 'form' %>

<%= link_to 'Back', views_path %>

app/views/views/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Idea:</b>
  <%= @view.idea_id %>
</p>

<p>
  <b>User:</b>
  <%= @view.user_id %>
</p>


<%= link_to 'Edit', edit_view_path(@view) %> |
<%= link_to 'Back', views_path %>